FROM postgres:12-alpine
#RUN ls && whoami && psql -U postgres -p 5432 -c 'create database store;'
#ADD entrypoint_gal.sh /
#CMD ["/entrypoint_gal.sh"]
#CMD ["/bin/bash"]
#CMD ["psql", "-U", "postgres", "-p", "5432", "-c", "'create database store;'"]
