version: '3.4'

services:
  postgres-db:
    container_name: postgres-db
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - 15432:5432
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/psql-dump.sql
  store-sv:
    container_name: store-sv
    expose:
      - 18181
    build:
      context: .
      dockerfile: ./docker/store/Dockerfile
    ports:
      - 18181:18181
    depends_on:
      - postgres-db
