version: '3'
services:

  zookeeper:
    container_name: zookeeper-service
    image: eventuateio/eventuate-zookeeper:0.4.0.RELEASE
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    container_name: kafka-service
    image: eventuateio/eventuate-kafka:0.3.0.RELEASE
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=localhost
      - KAFKA_HEAP_OPTS=-Xmx520m -Xms520m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  postgres-db:
    container_name: postgres-db
    build:
      context: 01-store/docker/postgres
      dockerfile: Dockerfile
    ports:
      - 15432:5432
    volumes:
      - ./01-store/docker/postgres/init.sql:/docker-entrypoint-initdb.d/psql-dump.sql
